#!/bin/bash
# Generate and install the Podman Quadlet unit for the UniFi Video controller.
#
#   sudo ./quadlet/install-quadlet.sh
#   sudo DATA_DIR=/srv/nvr/data VIDEO_DIR=/mnt/bulk/videos ./quadlet/install-quadlet.sh
#   DRY_RUN=1 ./quadlet/install-quadlet.sh          # print the unit, install nothing
#
# Substitutes the paths into unifi-nvr.container.in and works out the systemd mount-unit
# dependency for the recordings volume. That last part is the reason this script exists:
# systemd derives the unit name from the path (/var/mnt/storage -> var-mnt-storage.mount),
# and if the ordering is wrong or missing, the controller can start before the recordings
# filesystem is mounted and write video into the empty mount point on the root filesystem.

set -euo pipefail

HERE="$(cd -- "$(dirname -- "$0")" && pwd)"
TEMPLATE="$HERE/unifi-nvr.container.in"

# --- tunables ---------------------------------------------------------------------
DATA_DIR="${DATA_DIR:-/var/lib/unifi-nvr/data}"          # config, keystore, MongoDB
VIDEO_DIR="${VIDEO_DIR:-/var/mnt/storage/unifi-nvr/videos}"  # recordings (own filesystem)
LOG_DIR="${LOG_DIR:-/var/log/unifi-nvr}"                 # controller logs
IMAGE="${IMAGE:-localhost/ekiourk/unifi-video:3.5.2}"    # locally built, see README
UNIT_DIR="${UNIT_DIR:-/etc/containers/systemd}"
# ------------------------------------------------------------------------------------

die()  { echo "ERROR: $*" >&2; exit 1; }
note() { echo "  $*"; }
say()  { printf '\n=== %s ===\n' "$*"; }

[ -f "$TEMPLATE" ] || die "template not found: $TEMPLATE"

say "requirements"
command -v podman >/dev/null 2>&1 || die "podman is not installed"
PV=$(podman --version | awk '{print $3}')
PV_MAJOR=${PV%%.*}; PV_REST=${PV#*.}; PV_MINOR=${PV_REST%%.*}
if [ "$PV_MAJOR" -lt 4 ] || { [ "$PV_MAJOR" -eq 4 ] && [ "$PV_MINOR" -lt 4 ]; }; then
    die "podman $PV is too old — Quadlet needs >= 4.4 (Debian 12 ships 4.3)"
fi
note "podman $PV"
command -v systemd-escape >/dev/null 2>&1 || die "systemd-escape not found; is this systemd?"

say "paths"
note "data   $DATA_DIR"
note "video  $VIDEO_DIR"
note "logs   $LOG_DIR"
note "image  $IMAGE"

# Work out whether the recordings live on their own filesystem, and if so which mount
# unit to depend on. findmnt --target reports the mount point containing the path, so it
# answers this even before the directory itself exists.
say "recordings filesystem"
VIDEO_PROBE="$VIDEO_DIR"
while [ ! -d "$VIDEO_PROBE" ] && [ "$VIDEO_PROBE" != "/" ]; do
    VIDEO_PROBE=$(dirname "$VIDEO_PROBE")
done
VIDEO_MNT=$(findmnt -no TARGET --target "$VIDEO_PROBE" 2>/dev/null || echo /)
ROOT_MNT=$(findmnt -no TARGET --target / 2>/dev/null || echo /)

if [ "$VIDEO_MNT" = "$ROOT_MNT" ]; then
    MOUNT_DEPS="# recordings are on the root filesystem, so no mount dependency is needed"
    note "$VIDEO_DIR is on the root filesystem — no mount ordering added"
    note "(fine for a test setup; for 24/7 recording give it its own filesystem)"
else
    UNIT=$(systemd-escape -p --suffix=mount "$VIDEO_MNT")
    MOUNT_DEPS="# ${VIDEO_MNT} carries the recordings: do not start before it is mounted,
# or the controller writes video into the empty mount point on the root filesystem.
Requires=${UNIT}
After=${UNIT}"
    note "$VIDEO_DIR is under $VIDEO_MNT -> $UNIT"
fi

say "generating"
OUT=$(mktemp)
trap 'rm -f "$OUT"' EXIT
DATA_DIR="$DATA_DIR" VIDEO_DIR="$VIDEO_DIR" LOG_DIR="$LOG_DIR" IMAGE="$IMAGE" \
MOUNT_DEPS="$MOUNT_DEPS" python3 - "$TEMPLATE" "$OUT" <<'PY'
import os, sys
src, dst = sys.argv[1], sys.argv[2]
s = open(src).read()
for k in ("DATA_DIR", "VIDEO_DIR", "LOG_DIR", "IMAGE", "MOUNT_DEPS"):
    s = s.replace("@%s@" % k, os.environ[k])
s = s.replace("# This is a TEMPLATE. The placeholders below must be substituted before use — either by running\n# ../quadlet/install-quadlet.sh, or by hand (see README, \"Running under Podman\").\n",
              "# Generated by quadlet/install-quadlet.sh — edit the template, not this file.\n")
open(dst, "w").write(s)
PY

# A surviving @TOKEN@ means the template gained a placeholder this script does not know.
if grep -qE '@[A-Z_]+@' "$OUT"; then
    grep -nE '@[A-Z_]+@' "$OUT" >&2
    die "unreplaced placeholders above"
fi

if [ -n "${DRY_RUN:-}" ]; then
    say "dry run — generated unit"
    cat "$OUT"
    exit 0
fi

[ "$(id -u)" -eq 0 ] || die "installing needs root (or set DRY_RUN=1 to preview)"

say "creating directories"
install -d -m 0755 "$DATA_DIR" "$LOG_DIR" "$VIDEO_DIR"
# The recordings volume mounts inside the data volume, so the mount point must exist there.
install -d -m 0755 "$DATA_DIR/videos"
note "created (existing directories and their contents are left alone)"

say "installing"
install -d -m 0755 "$UNIT_DIR"
install -m 0644 "$OUT" "$UNIT_DIR/unifi-nvr.container"
note "$UNIT_DIR/unifi-nvr.container"
systemctl daemon-reload

say "validating"
GEN=/usr/lib/systemd/system-generators/podman-system-generator
[ -x "$GEN" ] || GEN=/usr/libexec/podman/quadlet
if [ -x "$GEN" ]; then
    "$GEN" --dryrun 2>&1 | grep -iE 'error|warn|unsupported|unknown' && die "quadlet reported problems" || true
    note "quadlet parsed the unit with no warnings"
    "$GEN" --dryrun 2>&1 | grep -E 'ExecStart' | head -1 | sed 's/^/    /'
else
    note "generator not found; skipping validation"
fi

cat <<EOF

Installed. Start it with:

    systemctl start unifi-nvr
    journalctl -u unifi-nvr -f

First start takes several minutes while the controller opens its database. Remember to
open the ports in the host firewall — the container uses host networking:

    firewall-cmd --permanent --add-port=7080/tcp --add-port=7443/tcp \\
      --add-port=7445-7447/tcp --add-port=6666/tcp --add-port=10001/udp
    firewall-cmd --reload
EOF
